In [1]:
import numpy as np


In [2]:
array_2x2 = np.array([[1, 2],
                      [3, 4]])
print("1. 2x2 Array:")
print(array_2x2)

1. 2x2 Array:
[[1 2]
 [3 4]]


In [3]:
random_3x4 = np.random.rand(3, 4)
print("2. Random 3x4 Array:")
print(random_3x4)


2. Random 3x4 Array:
[[0.59636564 0.28194126 0.87402084 0.80864789]
 [0.27726546 0.41339568 0.30794853 0.04710553]
 [0.49480079 0.73545126 0.00954079 0.4523806 ]]


In [4]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))
print("3. Array of Ones:")
print(ones_array)
print("\nArray of Zeroes:")
print(zeros_array)

3. Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Array of Zeroes:
[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
random_6x3 = np.random.rand(6, 3)
print("4. Random 6x3 Array:")
print(random_6x3)
print("\nTransposed Array (3x6):")
print(random_6x3.T)

4. Random 6x3 Array:
[[0.90524351 0.34288921 0.12110985]
 [0.09649985 0.84421799 0.23761049]
 [0.28185396 0.43015834 0.28852106]
 [0.39504065 0.51767331 0.7133416 ]
 [0.70366459 0.62477835 0.21815065]
 [0.4107737  0.60469963 0.38267125]]

Transposed Array (3x6):
[[0.90524351 0.09649985 0.28185396 0.39504065 0.70366459 0.4107737 ]
 [0.34288921 0.84421799 0.43015834 0.51767331 0.62477835 0.60469963]
 [0.12110985 0.23761049 0.28852106 0.7133416  0.21815065 0.38267125]]


In [6]:
n, p, m = 2, 3, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)

print("5. Matrix A (n x p):")
print(A)
print("\nMatrix B (p x m):")
print(B)
print("\nDot Product (n x m):")
print(dot_product)


5. Matrix A (n x p):
[[0.07431366 0.36538128 0.81257981]
 [0.14259301 0.00933783 0.89263653]]

Matrix B (p x m):
[[0.81657487 0.72889916 0.37472496 0.42110995]
 [0.7331681  0.08783083 0.02640906 0.05153941]
 [0.85813238 0.21108217 0.82099881 0.69615945]]

Dot Product (n x m):
[[1.02586961 0.25778001 0.70462362 0.61581086]
 [0.88928438 0.29317573 0.78653329 0.68194595]]
